---
# tasks file for builder
- name: Ensure package
  apt: name={{item}} state=installed
  with_items:
       - maven
       - git


- name: Ensure that work dir is present in builder
  file:
    path: /home/mywebapplication
    state: absent

- name: get git project
  git: repo='https://github.com/tarekkhoury/mywebapplication.git' dest=/home/mywebapplication


- name: make war
  shell:
    cmd:  mvn -f /home/mywebapplication/pom.xml clean package
    

- name: copy file to prod
  synchronize: src=/home/mywebapplication/target/mywebapplication.war dest=/var/lib/tomcat9/webapps/ mode=pull
  delegate_to: prod

